### ISSUE TITLE
Typings seems incorrect

### ISSUE THREAD

**Issue by sinedied** [sindresorhus/p-throttle#19]
Maybe I missed something, but the function returned by throttle is not type-compatible with the original, which seems kinda wrong.

I'm trying to do something like this:
```ts
const throttledPost = pThrottle(got.post, 10, 30000);
...
const post = shouldThrottle ? throttledPost : got.post; // ts error here, incompatible types
post('/some/api, ...);
```

Is there something I missed, like a providing types for pThrottle or is this a bug?
Thanks for helping.

**Comment by sindresorhus** [comment]
It is intended to be type-compatible, yes.

**Comment by MikeYermolayev** [comment]
Hi, is there any workaround right now how to use p-throttle with got?

Tried to do few options, but failed since it looses possibility to pass generic.
1.
```
const throttledFetch = pThrottle(got, REQ_PER_10_SEC, RATE_INTERVAL);

throttledFetch<{res: boolean}>('url'); //expected 0 type arguments
`` `

2.
```
const throttledFetch = pThrottle<Parameters<typeof got>, ReturnType<typeof got>>(got, REQ_PER_10_SEC, RATE_INTERVAL);

throttledFetch<{res: boolean}>('url'); //expected 0 type arguments
```
3.
```
const throttledFetch = <R>() => pThrottle<Parameters<typeof got>, R>(got, REQ_PER_10_SEC, RATE_INTERVAL); //error here. Argument of type 'Got' is not assignable to parameter of type '(options: Options) => R | PromiseLike<R>'
```

Thanks in advance

**Comment by MikeYermolayev** [comment]
For now I did this, but it feels sooo wrong )

```
const throttledFetch = (pThrottle(
        got,
        RES_PER_10_SEC,
        RATE_INTERVAL,
    ) as unknown) as typeof got;
```
